student.name: "Elizaveta"
student.last_name: "Grishkina"
student.group: "IKBO-16-19"
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345678
    driverClassName: org.postgresql.Driver